name: Actualizar Cartelera Perucho TV

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar el Scraper
        run: node scraper.js

      - name: Guardar los JSON generados en el repositorio
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add peliculas.json series.json
          git commit -m "Actualización automática de JSON" || echo "No hay cambios para subir"
          git push
